PID: /data42/frib/e21027/Analysis/cuts/Ge84.Cut.cxx
RIT:
  - Gate: 
      lowerbound: 30000.0
      upperbound: 65535.0
ION:
  lowerbound: 15000.0
  upperbound: 45000.0
BETA:
  lowerbound: 400.0
  upperbound: 10000.0
CORRELATION:
  Forward: 3.0
  Backward: 3.0
RADIUS: 0.5
